### ISSUE TITLE
info flashing in and out

### ISSUE THREAD

**Issue by oziee** [marcelblijleven/goodwe#78]
I have a SBP5000 and in HA the data flashes in with info and then out with unknown over and over..
ran some inverter_check tests.. inverter set to `None`.. see below

the logs ouput in HA
```
2024-05-13 17:43:58.602 DEBUG (MainThread) [custom_components.goodwe.coordinator] No response received (streak of 1)
2024-05-13 17:43:58.602 DEBUG (MainThread) [custom_components.goodwe.coordinator] Finished fetching GoodWe data in 5.095 seconds (success: True)
2024-05-13 17:44:06.949 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
self._protocol.datagram_received(data, addr)
File "/usr/local/lib/python3.12/site-packages/goodwe/protocol.py", line 111, in datagram_received
if self.command.validator(data):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/goodwe/protocol.py", line 408, in <lambda>
lambda x: self._validate_response(x, response_type),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/goodwe/protocol.py", line 428, in _validate_response
logger.debug("Response has unexpected length: %d, expected %d.", len(data), data[6] + 9)
~~~~^^^
IndexError: index out of range
2024-05-13 17:44:58.621 ERROR (MainThread) [homeassistant.components.number] Setup of platform goodwe is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2024-05-13 17:44:58.621 ERROR (MainThread) [homeassistant.components.select] Setup of platform goodwe is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2024-05-13 17:44:58.732 ERROR (MainThread) [homeassistant.components.switch] Setup of platform goodwe is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

ran some inverter_check and got different outputs

inverter set to default ET

```
2024-05-13 18:06:56,807 __init__(54) - DEBUG: Using selector: KqueueSelector
2024-05-13 18:06:56,807 connect(55) - DEBUG: Connecting to ET family inverter at 10.0.1.51:8899.
2024-05-13 18:06:56,807 _ensure_lock(43) - DEBUG: Creating lock instance for current event loop.
2024-05-13 18:06:56,808 _send_request(144) - DEBUG: Sending: READ 33 registers from 35000 (f70388b800213ac1)
2024-05-13 18:06:56,999 validate_modbus_rtu_response(181) - DEBUG: Response is too short: 35, expected 73.
2024-05-13 18:06:56,999 datagram_received(115) - DEBUG: Received invalid response: aa55f70342000113560000003900350030003000300042005000530047005700350030
2024-05-13 18:06:56,999 _send_request(144) - DEBUG: Sending: READ 33 registers from 35000 (f70388b800213ac1) - retry #1/3
2024-05-13 18:06:57,491 validate_modbus_rtu_response(181) - DEBUG: Response is too short: 45, expected 73.
2024-05-13 18:06:57,492 datagram_received(115) - DEBUG: Received invalid response: aa55f703420001135600000039003500300030003000420050005300470057003500300030000a000a00960000
2024-05-13 18:06:57,492 _send_request(144) - DEBUG: Sending: READ 33 registers from 35000 (f70388b800213ac1) - retry #2/3
2024-05-13 18:06:57,901 validate_modbus_rtu_response(181) - DEBUG: Response is too short: 48, expected 73.
2024-05-13 18:06:57,901 datagram_received(115) - DEBUG: Received invalid response: aa55f703420001135600000039003500300030003000420050005300470057003500300030000a000a009600000000ff
2024-05-13 18:06:57,902 _send_request(144) - DEBUG: Sending: READ 33 registers from 35000 (f70388b800213ac1) - retry #3/3
2024-05-13 18:06:58,311 validate_modbus_rtu_response(181) - DEBUG: Response is too short: 61, expected 73.
2024-05-13 18:06:58,311 datagram_received(115) - DEBUG: Received invalid response: aa55f703420001135600000039003500300030003000420050005300470057003500300030000a000a009600000000ffffffffffffffffffffffffffff
2024-05-13 18:06:58,311 _retry_mechanism(159) - DEBUG: Max number of retries (3) reached, request READ 33 registers from 35000 (f70388b800213ac1) failed.
2024-05-13 18:06:58,312 connection_lost(102) - DEBUG: Socket closed.
Traceback (most recent call last):
  File "/Users/oziee/Downloads/goodwe-master 4/inverter_check.py", line 43, in <module>
    inverter = asyncio.run(goodwe.connect(IP_ADDRESS, PORT, FAMILY, COMM_ADDR, TIMEOUT, RETRIES))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/__init__.py", line 56, in connect
    await inv.read_device_info()
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/et.py", line 495, in read_device_info
    response = await self._read_from_socket(self._READ_DEVICE_VERSION_INFO)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/inverter.py", line 129, in _read_from_socket
    raise RequestFailedException(f'No valid response received even after {self._protocol.retries} retries',
goodwe.exceptions.RequestFailedException: ('No valid response received even after 3 retries', 1)
```

inverter set to `None`
```
2024-05-13 18:24:19,020 __init__(54) - DEBUG: Using selector: KqueueSelector
2024-05-13 18:24:19,020 discover(70) - DEBUG: Probing inverter at 10.0.1.51:8899.
2024-05-13 18:24:19,020 _ensure_lock(43) - DEBUG: Creating lock instance for current event loop.
2024-05-13 18:24:19,021 _send_request(144) - DEBUG: Sending: aa55c07f0102000241
2024-05-13 18:24:19,199 _validate_response(432) - DEBUG: Response has unexpected length: 29, expected 86.
2024-05-13 18:24:19,199 datagram_received(115) - DEBUG: Received invalid response: aa557fc001824d3130313043475735303030532d425023313000000000
2024-05-13 18:24:19,199 _send_request(144) - DEBUG: Sending: aa55c07f0102000241 - retry #1/10
2024-05-13 18:24:19,718 _validate_response(432) - DEBUG: Response has unexpected length: 40, expected 86.
2024-05-13 18:24:19,718 datagram_received(115) - DEBUG: Received invalid response: aa557fc001824d3130313043475735303030532d4250233130000000000000000000000000003935
2024-05-13 18:24:19,719 _send_request(144) - DEBUG: Sending: aa55c07f0102000241 - retry #2/10
2024-05-13 18:24:20,095 datagram_received(112) - DEBUG: Received: aa557fc001824d3130313043475735303030532d42502331300000000000000000000000000039353030304250533232335730313832333630303431302d30343030312d3130093431302d30323033342d3136021010
2024-05-13 18:24:20,095 discover(85) - DEBUG: Detected ES/EM/BP inverter GW5000S-BP, S/N:95000BPS223W0182.
2024-05-13 18:24:20,096 _ensure_lock(43) - DEBUG: Creating lock instance for current event loop.
2024-05-13 18:24:20,097 _send_request(144) - DEBUG: Sending: aa55c07f0102000241
2024-05-13 18:24:20,607 _validate_response(432) - DEBUG: Response has unexpected length: 54, expected 86.
2024-05-13 18:24:20,607 datagram_received(115) - DEBUG: Received invalid response: aa557fc001824d3130313043475735303030532d42502331300000000000000000000000000039353030304250533232335730313832
2024-05-13 18:24:20,607 _send_request(144) - DEBUG: Sending: aa55c07f0102000241 - retry #1/10
2024-05-13 18:24:21,016 datagram_received(112) - DEBUG: Received: aa557fc001824d3130313043475735303030532d42502331300000000000000000000000000039353030304250533232335730313832333630303431302d30343030312d3130093431302d30323033342d3136021010
2024-05-13 18:24:21,017 discover(96) - DEBUG: Connected to inverter GW5000S-BP, S/N:95000BPS223W0182.
Identified inverter
- Model: GW5000S-BP
- SerialNr: 95000BPS223W0182
- Rated power: 0
- A/C output type: None
- Firmware: 1010C
- ARM firmware: None
- Modbus version: None
- DSP1 version: 10
- DSP2 version: 10
- DSP svn version: None
- Arm version: 12
- ARM svn version: None

2024-05-13 18:24:21,018 __init__(54) - DEBUG: Using selector: KqueueSelector
2024-05-13 18:24:21,019 _ensure_lock(43) - DEBUG: Creating lock instance for current event loop.
2024-05-13 18:24:21,019 _close_transport(168) - DEBUG: Failed to close transport.
2024-05-13 18:24:21,020 _send_request(144) - DEBUG: Sending: aa55c07f0106000245
2024-05-13 18:24:21,529 _validate_response(432) - DEBUG: Response has unexpected length: 73, expected 149.
2024-05-13 18:24:21,529 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea40021000000000200020b019f005000f600ca00410041000048004864020000010937002bfffa1389010937002e03b513890102015e000000000000bfb700003e
2024-05-13 18:24:21,529 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #1/10
2024-05-13 18:24:22,038 _validate_response(432) - DEBUG: Response has unexpected length: 26, expected 149.
2024-05-13 18:24:22,038 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea60021000000000200020b019f005000f600
2024-05-13 18:24:22,038 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #2/10
2024-05-13 18:24:22,553 _validate_response(432) - DEBUG: Response has unexpected length: 114, expected 149.
2024-05-13 18:24:22,553 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea50021000000000200020b019f005000f600ca00410041000048004864020000010936002bfff91389010936002d03a313890102015f000000000000bfb700003ed4001b00d000036ad003d90100300003cc00010000ffd900000040000018050d121813000000000000
2024-05-13 18:24:22,553 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #3/10
2024-05-13 18:24:23,065 _validate_response(432) - DEBUG: Response has unexpected length: 148, expected 149.
2024-05-13 18:24:23,065 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea40021000000000200020b019f005000f600ca00410041000048004864020000010938002bfff81389010938002e03b213890102015f000000000000bfb700003ed4001b00d000036ad003d90100300003da00010000ffda00000040000018050d1218130000000000000000000000000000000000000000000000000000d9fd0000ccec04001fc7ed00011c
2024-05-13 18:24:23,066 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #4/10
2024-05-13 18:24:23,573 _validate_response(432) - DEBUG: Response has unexpected length: 107, expected 149.
2024-05-13 18:24:23,574 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea60021000000000200020b019f005000f600ca00410041000048004864020000010937002bfff91388010937002d03a713880102015f000000000000bfb700003ed4001b00d000036ad003d90100300003cb00010000ffdb00000040000018050d1218
2024-05-13 18:24:23,574 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #5/10
2024-05-13 18:24:24,088 _validate_response(432) - DEBUG: Response has unexpected length: 62, expected 149.
2024-05-13 18:24:24,089 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea40021000000000200020b019f005000f600ca00410041000048004864020000010937002bfffa1389010937002e03b713890102015f
2024-05-13 18:24:24,089 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #6/10
2024-05-13 18:24:24,600 _validate_response(432) - DEBUG: Response has unexpected length: 20, expected 149.
2024-05-13 18:24:24,601 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea50021000000000200020b01
2024-05-13 18:24:24,601 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #7/10
2024-05-13 18:24:24,907 _validate_response(432) - DEBUG: Response has unexpected length: 58, expected 149.
2024-05-13 18:24:24,907 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea60021000000000200020b019f005000f600ca00410041000048004864020000010938002bfffa1388010938002e03b71388
2024-05-13 18:24:24,908 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #8/10
2024-05-13 18:24:25,401 _validate_response(432) - DEBUG: Response has unexpected length: 16, expected 149.
2024-05-13 18:24:25,402 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea500210000000002
2024-05-13 18:24:25,402 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #9/10
2024-05-13 18:24:25,931 _validate_response(432) - DEBUG: Response has unexpected length: 86, expected 149.
2024-05-13 18:24:25,932 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea50021000000000200020b019f005000f600ca0041004100004800486402000001093d002bfffa138901093d002e03b413890102015f000000000000bfb700003ed4001b00d000036ad003d90100
2024-05-13 18:24:25,932 _send_request(144) - DEBUG: Sending: aa55c07f0106000245 - retry #10/10
2024-05-13 18:24:26,422 _validate_response(432) - DEBUG: Response has unexpected length: 46, expected 149.
2024-05-13 18:24:26,422 datagram_received(115) - DEBUG: Received invalid response: aa557fc001868c0ea50021000000000200020b019f005000f600ca0041004100004800486402000001093d002bff
2024-05-13 18:24:26,422 _retry_mechanism(159) - DEBUG: Max number of retries (10) reached, request aa55c07f0106000245 failed.
2024-05-13 18:24:26,422 connection_lost(102) - DEBUG: Socket closed.
Traceback (most recent call last):
  File "/Users/oziee/Downloads/goodwe-master 4/inverter_check.py", line 62, in <module>
    response = asyncio.run(inverter.read_runtime_data())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/es.py", line 209, in read_runtime_data
    response = await self._read_from_socket(self._READ_DEVICE_RUNNING_DATA)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/inverter.py", line 129, in _read_from_socket
    raise RequestFailedException(f'No valid response received even after {self._protocol.retries} retries',
goodwe.exceptions.RequestFailedException: ('No valid response received even after 10 retries', 1)
```

**Comment by mletenay** [comment]
Your inverter is of "ES" kind.
You seem to receive lots of incomplete/fragmented responses, it is rare but unfortunately it happens.
I have just implemented an attempt to recovers from these fragmented packets (if that is actually what happens).
Please, update to latest version and try again.

**Comment by oziee** [comment]
@mletenay cheers.. thanks for trying..

seems to get some data but then nothing else ever comes in.. just sits there
```
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:goodwe:Connecting to ES family inverter at 10.0.1.51:8899.
DEBUG:goodwe.protocol:Creating lock instance for current event loop.
DEBUG:goodwe.protocol:Sending: aa55c07f0102000241
DEBUG:goodwe.protocol:Received response fragment: aa557fc001824d3130313043475735303030532d425023313000000000000000000000000000393530303042505332323357303138
```
waited..waited and waited more but nothing else ever logged..


I still get `index out of range` errors or the test just sit there and do nothing

```
python inverter_check.py
2024-05-20 14:57:19,352 __init__(54) - DEBUG: Using selector: KqueueSelector
2024-05-20 14:57:19,352 connect(52) - DEBUG: Connecting to ES family inverter at 10.0.1.51:8899.
2024-05-20 14:57:19,352 _ensure_lock(58) - DEBUG: Creating lock instance for current event loop.
2024-05-20 14:57:19,353 _send_request(176) - DEBUG: Sending: aa55c07f0102000241
2024-05-20 14:57:19,742 default_exception_handler(1771) - ERROR: Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 1169, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/protocol.py", line 131, in datagram_received
    if self.command.validator(data):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/protocol.py", line 487, in <lambda>
    lambda x: self._validate_response(x, response_type),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oziee/Downloads/goodwe-master 4/goodwe/protocol.py", line 507, in _validate_response
    raise PartialResponseException(len(data), data[6] + 9)
                                              ~~~~^^^
IndexError: index out of range
```

**Comment by mletenay** [comment]
Fixed in v0.4.5

**Comment by oziee** [comment]
Thanks.. I'll give it a try tonight
